'use client';
import { useEffect, useRef, useState } from 'react';
import { SiteCredits } from '@/components/site-credits';
import { QuestionnaireMethod } from '@/components/questionnaire-method';
import { ArrowRight, ArrowLeft, Check, Compass, Download, ExternalLink, RotateCcw, Sprout } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Progress } from '@/components/ui/progress';
import { ChartContainer } from '@/components/ui/chart';
import { Radar, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis } from 'recharts';
import { dimensions, questions, interestLabels, skillLabels, evaluate, contextAnswer, nextSteps } from '@/lib/vocational';

export default function Home() {
 const [dream,setDream] = useState('');
 const [stage,setStage] = useState<'entry'|'intro'|'quiz'|'result'>('entry');
 const [index,setIndex] = useState(0);
 const [answers,setAnswers] = useState<Record<string,number>>({});
 const [tab,setTab] = useState<'overview'|'answers'>('overview');
 const heading = useRef<HTMLHeadingElement>(null);
 useEffect(()=>{ if(stage!=='entry') {heading.current?.focus(); window.scrollTo({top:0,behavior:'instant'});} },[stage,index,tab]);
 const question = questions[index];
 const labels = question.options ?? (question.kind==='skill'?skillLabels:interestLabels);
 const result = stage==='result'?evaluate(answers):null;
 function restart(){setDream('');setAnswers({});setIndex(0);setTab('overview');setStage('entry');}
 function download(){
  if(!result)return;
  const report = ['HORIZONTE — MEU MAPA DE POSSIBILIDADES',`Eu quero ser: ${dream}`,'','EXPLORAÇÃO EDUCATIVA. Não é teste psicológico validado nem previsão de sucesso.','',...dimensions.map(d=>`${d.name}: ${result.scores[d.key]}/100`),'','CAMINHOS PARA INVESTIGAR',...result.ranked.slice(0,3).map(c=>`${c.name} (${c.score}/100 no índice exploratório)\n${c.fields}\nExperimente: ${c.experiment}`),'','PRÓXIMOS PASSOS',...nextSteps(answers),'','MINHAS RESPOSTAS',...questions.map(q=>`${q.title}\n${(q.options??(q.kind==='skill'?skillLabels:interestLabels))[answers[q.id]]}`),'','Método: 3 itens por interesse, notas 0 a 4, soma / 12 × 100. Caminhos: 60% do interesse principal + 40% do secundário. Empates não indicam preferência. Habilidades e contexto não reduzem o índice.','Fontes: https://www.onetcenter.org/IP.html | https://acessounico.mec.gov.br/ | https://emec.mec.gov.br/'].join('\n');
  const url=URL.createObjectURL(new Blob([report],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='meu-mapa-horizonte.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 }
 if(stage==='entry')return <main className="entry"><form className="entry-form" onSubmit={e=>{e.preventDefault();if(dream.trim()){setDream(dream.trim());setStage('intro');}}}><div className="entry-welcome"><span className="eyebrow">BEM-VINDO AO HORIZONTE</span><p>Explore seus interesses e descubra possibilidades de formação depois do ENEM. Responda a 29 perguntas e receba um mapa com sugestões e próximos passos — um ponto de partida, não uma escolha definitiva.</p></div><label htmlFor="dream"><h1>Eu quero ser<span>…</span></h1></label><div className="dream-field"><Input id="dream" aria-describedby="entry-privacy" value={dream} onChange={e=>setDream(e.target.value)} placeholder="Uma profissão, um sonho ou ainda não sei" maxLength={120} required autoComplete="off"/><Button type="submit" aria-label="Começar minha descoberta" disabled={!dream.trim()}><ArrowRight/></Button></div><div className="entry-privacy" id="entry-privacy"><strong>Suas respostas ficam com você.</strong><p>O Horizonte não envia, armazena em banco de dados nem divulga o texto que você digita ou suas respostas. Tudo fica apenas na memória desta página e se perde ao fechar ou atualizar. Não é necessário cadastro.</p><small>Se baixar seu mapa, o arquivo ficará no seu dispositivo. A hospedagem pode registrar dados técnicos de acesso, separados das respostas ao questionário.</small></div></form></main>;
 return <div className="app-shell"><header className="topbar"><span className="brand"><Compass size={24}/> horizonte<span className="brand-dot">.</span></span><span className="top-note">Seu futuro, em construção</span></header>
 {stage==='intro'&&<main className="intro page-width"><span className="eyebrow">UM PONTO DE PARTIDA, NÃO UM DESTINO FINAL</span><h1 ref={heading} tabIndex={-1}>Vamos abrir<br/>seu <em>horizonte.</em></h1><p className="lead">Você escreveu <strong>“{dream}”</strong>.<br/>Agora, vamos olhar para o que desperta sua curiosidade e para as possibilidades depois do ENEM.</p><div className="intro-facts"><div><strong>29 perguntas</strong><span>Uma de cada vez, no seu ritmo.</span></div><div><strong>Sem respostas certas</strong><span>Responda por você, sem expectativas alheias.</span></div><div><strong>Sem cadastro</strong><span>As respostas ficam só nesta página.</span></div></div><p className="note">Este é um roteiro educativo de autoconhecimento, não um teste psicológico validado. Não mede aptidão nem define uma profissão. Ao atualizar ou fechar a página, suas respostas serão perdidas; ao final, você pode baixar seu mapa.</p><div className="actions"><Button className="primary-btn" onClick={()=>setStage('quiz')}>Explorar minhas possibilidades <ArrowRight/></Button><Button variant="ghost" onClick={()=>setStage('entry')}><ArrowLeft/> Editar minha resposta</Button></div></main>}
 {stage==='quiz'&&<main className="quiz page-width"><div className="quiz-meta"><span>{question.section}</span><span>{String(index+1).padStart(2,'0')} <span className="muted">/ {questions.length}</span></span></div><Progress value={index/questions.length*100} aria-label={`${index} de ${questions.length} perguntas concluídas`}/><form key={question.id} onSubmit={e=>{e.preventDefault();if(answers[question.id]===undefined)return;if(index===questions.length-1){setStage('result');setTab('overview');}else setIndex(index+1);}}><div className="question-block"><span className="eyebrow">{question.kind==='interest'?'IMAGINE ESTA ATIVIDADE':question.kind==='skill'?'HABILIDADES SE CONSTROEM':'ESCOLHAS QUE CABEM NA SUA VIDA'}</span><h1 ref={heading} tabIndex={-1} id="question-title">{question.title}</h1><p id="question-hint">{question.hint}</p></div><fieldset className="options" aria-labelledby="question-title" aria-describedby="question-hint"><legend className="sr-only">Selecione uma resposta</legend>{labels.map((label,i)=><label key={label} className={`option ${answers[question.id]===i?'selected':''}`}><input type="radio" name={question.id} value={i} checked={answers[question.id]===i} onChange={()=>setAnswers(a=>({...a,[question.id]:i}))}/><span className="option-index" aria-hidden="true">{i+1}</span><span>{label}</span>{answers[question.id]===i&&<Check size={19} className="option-check"/>}</label>)}</fieldset><div className="quiz-footer"><Button type="button" variant="ghost" onClick={()=>index===0?setStage('intro'):setIndex(index-1)}><ArrowLeft/> Voltar</Button><Button type="submit" className="primary-btn" disabled={answers[question.id]===undefined}>{index===questions.length-1?'Ver meu mapa':'Continuar'}<ArrowRight/></Button></div></form><p className="quiet-note">Você pode voltar e mudar qualquer resposta antes de concluir.</p></main>}
 {stage==='result'&&result&&<main className="dashboard page-width"><div className="result-heading"><div><span className="eyebrow">UMA ESCOLHA COMEÇA COM AUTOCONHECIMENTO</span><h1 ref={heading} tabIndex={-1}>Seu mapa de <em>possibilidades.</em></h1><p>Você trouxe “{dream}”. Aqui estão caminhos para investigar, a partir das suas respostas.</p></div><Button className="download" variant="outline" onClick={download}><Download/> Baixar meu mapa</Button></div><div className="view-tabs" role="group" aria-label="Visualização do resultado"><Button variant="ghost" aria-pressed={tab==='overview'} onClick={()=>setTab('overview')}>Meu dashboard</Button><Button variant="ghost" aria-pressed={tab==='answers'} onClick={()=>setTab('answers')}>Minhas 29 respostas</Button></div>
 {tab==='overview'?<><div className="dashboard-grid"><section className="panel profile-panel"><span className="eyebrow">01 / SEUS INTERESSES</span><h2>O que desperta você</h2><p className="muted">Intensidade declarada nas atividades, de 0 a 100.</p><ChartContainer config={{score:{label:'Interesse',color:'#245c4d'}}} className="radar" aria-hidden="true"><RadarChart data={dimensions.map(d=>({name:d.name,score:result.scores[d.key]}))}><PolarGrid/><PolarAngleAxis dataKey="name" tick={{fontSize:11,fill:'#153e38'}}/><PolarRadiusAxis domain={[0,100]} tick={false} axisLine={false}/><Radar dataKey="score" stroke="#245c4d" fill="#7e9b66" fillOpacity={0.3} isAnimationActive={false}/></RadarChart></ChartContainer><div className="score-list">{dimensions.map(d=><div key={d.key} className="score-row"><span>{d.name}</span><Progress value={result.scores[d.key]} aria-label={`${d.name}: ${result.scores[d.key]} de 100`}/><strong>{result.scores[d.key]}</strong></div>)}</div></section><section className="panel reality-panel"><span className="eyebrow">02 / O QUE IMPORTA AGORA</span><h2>Seu contexto também conta.</h2><dl>{[['subject','Área que desperta interesse'],['value','Prioridade no trabalho'],['study','Rotina de estudos'],['access','Planejamento'],['certainty','Como você se sente']].map(([id,label])=><div key={id}><dt>{label}</dt><dd>{contextAnswer(id,answers)}</dd></div>)}</dl></section></div>
 <section className="path-section"><div className="section-title"><div><span className="eyebrow">03 / CAMINHOS PARA EXPLORAR</span><h2>Mais de um futuro possível.</h2></div><span className="tag">Sugestões, não sentenças</span></div>{Math.max(...Object.values(result.scores))<50&&<p className="notice">Suas respostas ainda não mostram interesses intensos nestas atividades. Os caminhos abaixo são convites para experimentar, não indicações fortes.</p>}{new Set(Object.values(result.scores)).size===1&&<p className="notice">Todos os interesses empataram. A ordem dos caminhos é apenas alfabética; nenhum se destaca pelas respostas.</p>}<div className="career-grid">{result.ranked.slice(0,3).map((c,i)=><article className="career-card" key={c.name}><div className="career-top"><span>CAMINHO {String(i+1).padStart(2,'0')}</span><span>{c.score}<small>/100</small></span></div><h3>{c.name}</h3><p className="course-list">{c.fields}</p><div className="reason"><strong>Por que explorar</strong><p>Combina os interesses {dimensions.find(d=>d.key===c.primary)?.name.toLowerCase()} ({result.scores[c.primary]}) e {dimensions.find(d=>d.key===c.secondary)?.name.toLowerCase()} ({result.scores[c.secondary]}).</p></div><details><summary>Conhecer este caminho <ArrowRight size={15}/></summary><h4>Experimente antes de decidir</h4><p>{c.experiment}</p><h4>Ao comparar currículos</h4><p>{c.attention}</p></details></article>)}</div><p className="note">Índice exploratório, não probabilidade de sucesso. Cursos de um mesmo grupo têm diferenças importantes. As sugestões não representam todas as profissões existentes.</p><details className="more-paths"><summary>Ver todos os 12 caminhos e seus índices</summary><ul>{result.ranked.map(c=><li key={c.name}><span>{c.name}</span><strong>{c.score}/100</strong></li>)}</ul></details></section>
 <section className="panel skills-panel"><span className="eyebrow">04 / HABILIDADES EM CONSTRUÇÃO</span><h2>Um retrato de hoje. Não um limite.</h2><div className="skill-grid">{dimensions.map(d=><div key={d.key}><strong>{d.name}</strong><span>{skillLabels[answers[`skill${d.key}`]]}</span><p>{d.description}</p></div>)}</div><p className="note">Autopercepção não é uma avaliação de desempenho. Uma habilidade pouco explorada é uma oportunidade de aprendizado; não reduz seu índice de interesse.</p></section>
 <section className="next-panel"><div><Sprout size={28}/><span className="eyebrow">05 / DO MAPA PARA A VIDA</span><h2>Seu próximo passo<br/>pode ser pequeno.</h2><p>Não decida só pelo nome do curso. Conheça as disciplinas, a rotina e as pessoas.</p></div><ol>{nextSteps(answers).map((step,i)=><li key={step}><span>0{i+1}</span><p>{step}</p></li>)}</ol></section>
 <section className="official-links"><h2>Para seguir com informações oficiais</h2><div><a href="https://acessounico.mec.gov.br/" target="_blank" rel="noreferrer">Acesso Único · ingresso e programas <ExternalLink size={16}/></a><a href="https://emec.mec.gov.br/" target="_blank" rel="noreferrer">e-MEC · instituições e cursos superiores <ExternalLink size={16}/></a></div><p className="note">Consulte os editais vigentes. Este mapa não estima nota de corte, elegibilidade a bolsas, salário ou empregabilidade. Não é vinculado ao MEC.</p></section>
 <p className="method"><a href="#como-esse-teste-foi-elaborado">Como esse teste foi elaborado: método e bibliografia</a></p></>:<section className="answer-review"><h2>O que você contou sobre você</h2><p>Edite uma resposta para recalcular seu mapa. As demais serão preservadas.</p>{questions.map((q,i)=><article key={q.id}><div><span className="eyebrow">{String(i+1).padStart(2,'0')} / {q.section}</span><h3>{q.title}</h3><p>{(q.options??(q.kind==='skill'?skillLabels:interestLabels))[answers[q.id]]}</p></div><Button variant="outline" onClick={()=>{setIndex(i);setStage('quiz');}}>Editar<span className="sr-only"> resposta {i+1}</span></Button></article>)}</section>}
 <footer className="result-footer"><p>Você é maior do que qualquer resultado.</p><Button variant="ghost" onClick={()=>{if(window.confirm('Começar de novo apagará as respostas desta página. Baixe seu mapa antes, se quiser guardá-lo. Continuar?'))restart();}}><RotateCcw/> Começar de novo</Button></footer></main>}
 {stage !== 'quiz' && <QuestionnaireMethod />}
 <SiteCredits />
 </div>;
}
